# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 08:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affinities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phys', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(-9)])),
                ('gun', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(-9)])),
                ('fire', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(-9)])),
                ('ice', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(-9)])),
                ('force', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(-9)])),
                ('elec', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(-9)])),
                ('light', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(-9)])),
                ('dark', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(-9)])),
                ('almighty', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(-9)])),
                ('heal', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(-9)])),
                ('ailment', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(-9)])),
                ('support', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(-9)])),
            ],
        ),
        migrations.CreateModel(
            name='Demon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('race', models.CharField(choices=[('Deity', 'Deity'), ('Amatsu', 'Amatsu'), ('Megami', 'Megami'), ('Nymph', 'Nymph'), ('Enigma', 'Enigma'), ('Entity', 'Entity'), ('Primal', 'Primal'), ('Fury', 'Fury'), ('Kunitsu', 'Kunitsu'), ('Kishin', 'Kishin'), ('Zealot', 'Zealot'), ('Lady', 'Lady'), ('Reaper', 'Reaper'), ('Vile', 'Vile'), ('Tyrant', 'Tyrant'), ('Genma', 'Genma'), ('Yoma', 'Yoma'), ('Fairy', 'Fairy'), ('Night', 'Night'), ('Herald', 'Herald'), ('Divine', 'Divine'), ('Fallen', 'Fallen'), ('Avian', 'Avian'), ('Flight', 'Flight'), ('Raptor', 'Raptor'), ('Jirae', 'Jirae'), ('Brute', 'Brute'), ('Femme', 'Femme'), ('Jaki', 'Jaki'), ('Dragon', 'Dragon'), ('Snake', 'Snake'), ('Drake', 'Drake'), ('Avatar', 'Avatar'), ('Holy', 'Holy'), ('Food', 'Food'), ('Beast', 'Beast'), ('Wilder', 'Wilder'), ('Tree', 'Tree'), ('Wood', 'Wood'), ('Ghost', 'Ghost'), ('Spirit', 'Spirit'), ('Undead', 'Undead'), ('Vermin', 'Vermin'), ('Foul', 'Foul'), ('Element', 'Element'), ('Fiend', 'Fiend'), ('Famed', 'Famed')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Resistances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phys', models.CharField(choices=[('-', '-'), ('weak', 'weak'), ('resist', 'resist'), ('null', 'null'), ('drain', 'drain'), ('repel', 'repel')], default='-', max_length=10)),
                ('gun', models.CharField(choices=[('-', '-'), ('weak', 'weak'), ('resist', 'resist'), ('null', 'null'), ('drain', 'drain'), ('repel', 'repel')], default='-', max_length=10)),
                ('fire', models.CharField(choices=[('-', '-'), ('weak', 'weak'), ('resist', 'resist'), ('null', 'null'), ('drain', 'drain'), ('repel', 'repel')], default='-', max_length=10)),
                ('ice', models.CharField(choices=[('-', '-'), ('weak', 'weak'), ('resist', 'resist'), ('null', 'null'), ('drain', 'drain'), ('repel', 'repel')], default='-', max_length=10)),
                ('force', models.CharField(choices=[('-', '-'), ('weak', 'weak'), ('resist', 'resist'), ('null', 'null'), ('drain', 'drain'), ('repel', 'repel')], default='-', max_length=10)),
                ('elec', models.CharField(choices=[('-', '-'), ('weak', 'weak'), ('resist', 'resist'), ('null', 'null'), ('drain', 'drain'), ('repel', 'repel')], default='-', max_length=10)),
                ('light', models.CharField(choices=[('-', '-'), ('weak', 'weak'), ('resist', 'resist'), ('null', 'null'), ('drain', 'drain'), ('repel', 'repel')], default='-', max_length=10)),
                ('dark', models.CharField(choices=[('-', '-'), ('weak', 'weak'), ('resist', 'resist'), ('null', 'null'), ('drain', 'drain'), ('repel', 'repel')], default='-', max_length=10)),
                ('demon', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='compendium.Demon')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('affinity', models.CharField(choices=[(0, 'Passive'), (1, 'Phys'), (2, 'Gun'), (3, 'Fire'), (4, 'Ice'), (5, 'Force'), (6, 'Elec'), (7, 'Light'), (8, 'Dark'), (9, 'Almighty'), (10, 'Heal'), (11, 'Ailment'), (12, 'Support'), (13, 'Special')], default='passsive', max_length=10)),
                ('power', models.CharField(choices=[(0, ''), (1, 'Weak'), (2, 'Medium'), (3, 'Heavy'), (4, 'Severe')], default='', max_length=10)),
                ('hits', models.CharField(default='', max_length=10)),
                ('target', models.CharField(choices=[(0, 'Self'), (1, 'Single'), (2, 'Multi'), (3, 'All')], default='single', max_length=10)),
                ('cost', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('unique_cost', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('rank', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
                ('mp', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
                ('strength', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
                ('dexterity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
                ('magic', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
                ('agility', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
                ('luck', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(999), django.core.validators.MinValueValidator(1)])),
                ('demon', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='compendium.Demon')),
            ],
        ),
        migrations.AddField(
            model_name='affinities',
            name='demon',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='compendium.Demon'),
        ),
    ]
