# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0002_auto_20161110_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementFusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_1', models.CharField(choices=[(b'Deity', b'Deity'), (b'Amatsu', b'Amatsu'), (b'Megami', b'Megami'), (b'Nymph', b'Nymph'), (b'Enigma', b'Enigma'), (b'Entity', b'Entity'), (b'Primal', b'Primal'), (b'Fury', b'Fury'), (b'Kunitsu', b'Kunitsu'), (b'Kishin', b'Kishin'), (b'Zealot', b'Zealot'), (b'Lady', b'Lady'), (b'Reaper', b'Reaper'), (b'Vile', b'Vile'), (b'Tyrant', b'Tyrant'), (b'Genma', b'Genma'), (b'Yoma', b'Yoma'), (b'Fairy', b'Fairy'), (b'Night', b'Night'), (b'Herald', b'Herald'), (b'Divine', b'Divine'), (b'Fallen', b'Fallen'), (b'Avian', b'Avian'), (b'Flight', b'Flight'), (b'Raptor', b'Raptor'), (b'Jirae', b'Jirae'), (b'Brute', b'Brute'), (b'Femme', b'Femme'), (b'Jaki', b'Jaki'), (b'Dragon', b'Dragon'), (b'Snake', b'Snake'), (b'Drake', b'Drake'), (b'Avatar', b'Avatar'), (b'Holy', b'Holy'), (b'Food', b'Food'), (b'Beast', b'Beast'), (b'Wilder', b'Wilder'), (b'Tree', b'Tree'), (b'Wood', b'Wood'), (b'Ghost', b'Ghost'), (b'Spirit', b'Spirit'), (b'Undead', b'Undead'), (b'Vermin', b'Vermin'), (b'Foul', b'Foul'), (b'Element', b'Element'), (b'Fiend', b'Fiend'), (b'Famed', b'Famed')], max_length=10)),
                ('race_2', models.CharField(choices=[(b'Deity', b'Deity'), (b'Amatsu', b'Amatsu'), (b'Megami', b'Megami'), (b'Nymph', b'Nymph'), (b'Enigma', b'Enigma'), (b'Entity', b'Entity'), (b'Primal', b'Primal'), (b'Fury', b'Fury'), (b'Kunitsu', b'Kunitsu'), (b'Kishin', b'Kishin'), (b'Zealot', b'Zealot'), (b'Lady', b'Lady'), (b'Reaper', b'Reaper'), (b'Vile', b'Vile'), (b'Tyrant', b'Tyrant'), (b'Genma', b'Genma'), (b'Yoma', b'Yoma'), (b'Fairy', b'Fairy'), (b'Night', b'Night'), (b'Herald', b'Herald'), (b'Divine', b'Divine'), (b'Fallen', b'Fallen'), (b'Avian', b'Avian'), (b'Flight', b'Flight'), (b'Raptor', b'Raptor'), (b'Jirae', b'Jirae'), (b'Brute', b'Brute'), (b'Femme', b'Femme'), (b'Jaki', b'Jaki'), (b'Dragon', b'Dragon'), (b'Snake', b'Snake'), (b'Drake', b'Drake'), (b'Avatar', b'Avatar'), (b'Holy', b'Holy'), (b'Food', b'Food'), (b'Beast', b'Beast'), (b'Wilder', b'Wilder'), (b'Tree', b'Tree'), (b'Wood', b'Wood'), (b'Ghost', b'Ghost'), (b'Spirit', b'Spirit'), (b'Undead', b'Undead'), (b'Vermin', b'Vermin'), (b'Foul', b'Foul'), (b'Element', b'Element'), (b'Fiend', b'Fiend'), (b'Famed', b'Famed')], max_length=10)),
                ('demon', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='compendium.Demon')),
            ],
        ),
    ]
