# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compendium', '0003_elementfusion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elementfusion',
            old_name='race_1',
            new_name='race',
        ),
        migrations.RemoveField(
            model_name='elementfusion',
            name='race_2',
        ),
    ]
